name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1.2.1


      - name: Build
        run: Compile.bat
        
      - name: Download Output
        uses: actions/upload-artifact@v2
        with:
          name: Bootloader
          path: bin/bootloader.flp
