name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run ilammy/setup-nasm@v1.2.1
        run: sudo apt-get install nasm

      - name: Build
        run:  bash configure && bash Compile.sh
        
      - name: Download Output
        uses: actions/upload-artifact@v2
        with:
          name: Bootloader
          path: bin/isoOutput
